"""Common library unit tests."""

python_tests(
    name="unit",
    sources=[
        "test_*.py",
        "*_test.py",
    ],
    dependencies=[
        "//:reqs0#pytest",
        "//libs/common/src/common:common",
    ],
)
