"""Mapper unit tests (MAL + AniList)."""

python_tests(
    dependencies=[
        "//libs/enrichment/src/enrichment/mappers",
        "//libs/enrichment/src/enrichment/crawlers/mal_crawler",
        "//libs/enrichment/src/enrichment/api_helpers/anilist",
        "//libs/enrichment/src/enrichment/api_helpers/kitsu",
        "//libs/common/src/common",
    ],
)
