"""MAL mapper unit tests."""

python_tests(
    dependencies=[
        "//libs/enrichment/src/enrichment/mappers",
        "//libs/enrichment/src/enrichment/crawlers/mal_crawler",
        "//libs/common/src/common",
    ],
)
