python_sources(
    sources=["**/*.py"],
    dependencies=[
        "//libs/common/src/common",
        "//libs/qdrant_db/src/qdrant_db",
        "//libs/vector_processing/src/vector_processing",
    ],
)
