python_tests(
    name="unit",
    dependencies=[
        "//:reqs0#pytest",
        "//:reqs0#pytest-asyncio",
        "//apps/enrichment_service/src/enrichment_service:enrichment_service",
    ],
)
