from collections.abc import Sequence

import numpy as np
from PIL import Image

def ccip_difference(image1: Image.Image, image2: Image.Image) -> float: ...
def ccip_batch_extract_features(
    images: Sequence[str | Image.Image], size: int = 384, model: str = ...
) -> np.ndarray: ...
def ccip_batch_differences(
    images: Sequence[str | Image.Image | np.ndarray], size: int = 384, model: str = ...
) -> np.ndarray: ...
def ccip_default_threshold(model: str = ...) -> float: ...
