# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.v1 import agent_search_pb2 as agent_dot_v1_dot_agent__search__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/agent_search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentSearchServiceStub(object):
    """Internal-only service. Called by the Rust BFF via gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchAI = channel.unary_unary(
                '/agent.v1.AgentSearchService/SearchAI',
                request_serializer=agent_dot_v1_dot_agent__search__pb2.SearchAIRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__search__pb2.SearchAIResponse.FromString,
                _registered_method=True)


class AgentSearchServiceServicer(object):
    """Internal-only service. Called by the Rust BFF via gRPC.
    """

    def SearchAI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchAI': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchAI,
                    request_deserializer=agent_dot_v1_dot_agent__search__pb2.SearchAIRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__search__pb2.SearchAIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.AgentSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.AgentSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentSearchService(object):
    """Internal-only service. Called by the Rust BFF via gRPC.
    """

    @staticmethod
    def SearchAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentSearchService/SearchAI',
            agent_dot_v1_dot_agent__search__pb2.SearchAIRequest.SerializeToString,
            agent_dot_v1_dot_agent__search__pb2.SearchAIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
