python_tests(
    name="unit",
    sources=["**/*_test.py", "**/test_*.py"],
    dependencies=[
        "//:reqs0#pytest",
        "//:reqs0#pytest-asyncio",
        "//:reqs0#pytest-mock",
        "libs/vector_processing/src/vector_processing:vector_processing",
    ],
)
