# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/admin.proto\x12\x05\x61\x64min\x1a\x1cgoogle/protobuf/struct.proto\"\x11\n\x0fGetStatsRequest\"\xb5\x01\n\x10GetStatsResponse\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\x17\n\x0ftotal_documents\x18\x02 \x01(\x03\x12\x13\n\x0bvector_size\x18\x03 \x01(\x05\x12\x17\n\x0f\x64istance_metric\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x31\n\x10\x61\x64\x64itional_stats\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct2M\n\x0c\x41\x64minService\x12=\n\x08GetStats\x12\x16.admin.GetStatsRequest\x1a\x17.admin.GetStatsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATSREQUEST']._serialized_start=59
  _globals['_GETSTATSREQUEST']._serialized_end=76
  _globals['_GETSTATSRESPONSE']._serialized_start=79
  _globals['_GETSTATSRESPONSE']._serialized_end=260
  _globals['_ADMINSERVICE']._serialized_start=262
  _globals['_ADMINSERVICE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
