# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/agent.proto\x12\x05\x61gent\"F\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x17\n\nimage_data\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_image_data\"I\n\x0eSearchResponse\x12\x11\n\tanime_ids\x18\x01 \x03(\t\x12\x16\n\treasoning\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_reasoning2G\n\x0c\x41gentService\x12\x37\n\x06Search\x12\x14.agent.SearchRequest\x1a\x15.agent.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=29
  _globals['_SEARCHREQUEST']._serialized_end=99
  _globals['_SEARCHRESPONSE']._serialized_start=101
  _globals['_SEARCHRESPONSE']._serialized_end=174
  _globals['_AGENTSERVICE']._serialized_start=176
  _globals['_AGENTSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
