python_test_utils(
    name="test_utils",
)

python_tests(
    dependencies=[
        "//:reqs0#pytest-asyncio",
        "//:reqs0#qdrant-client",
        "//:reqs0#pydantic",
        "libs/common/src/common:common",
        "libs/vector_processing/src/vector_processing",
        "libs/qdrant_db/src/qdrant_db",
    ],
)
