"""AniList source unit tests."""

python_tests(
    dependencies=[
        "//tests/libs/enrichment/unit:conftest",
        "//libs/enrichment/src/enrichment",
        "//libs/http_cache/src/http_cache",
        "//libs/common/src/common",
        "//:reqs0#pytest-asyncio",
        "//:reqs0#pytest-mock",
    ],
)
