"""Type stubs for PyTorch tensor operations."""

from typing import Any

class Tensor:
    """Type stub for torch.Tensor."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def item(self) -> float: ...
    def cpu(self) -> Tensor: ...
    def numpy(self) -> Any: ...
    def tolist(self) -> list[Any]: ...
    def mean(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def max(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def softmax(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def argmax(self, *args: Any, **kwargs: Any) -> Tensor: ...

def no_grad() -> Any: ...
def sigmoid(x: Tensor) -> Tensor: ...
def cat(tensors: list[Tensor], dim: int = 0) -> Tensor: ...
