"""Type stubs for numpy ndarray operations."""

from typing import Any, TypeVar, Generic

_DType = TypeVar('_DType')

class ndarray(Generic[_DType]):
    """Type stub for numpy.ndarray."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def mean(self, *args: Any, **kwargs: Any) -> ndarray[Any]: ...
    def tolist(self) -> list[Any]: ...

def array(object: Any, dtype: Any = None) -> ndarray[Any]: ...
def mean(a: ndarray[Any], *args: Any, **kwargs: Any) -> ndarray[Any]: ...
