"""Type stubs for numpy ndarray operations."""

from typing import Any, Generic, TypeVar, overload

_DType = TypeVar("_DType")

class ndarray(Generic[_DType]):
    """Type stub for numpy.ndarray."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def mean(self, *args: Any, **kwargs: Any) -> ndarray[Any]: ...
    def tolist(self) -> list[Any]: ...
    def __truediv__(self, other: Any) -> ndarray[Any]: ...
    def __float__(self) -> float: ...
    def __getitem__(self, key: Any) -> Any: ...

class linalg:
    """Linear algebra operations."""
    @staticmethod
    def norm(
        x: ndarray[Any] | list[float] | list[Any], *args: Any, **kwargs: Any
    ) -> float: ...

def array(object: Any, dtype: Any = None) -> ndarray[Any]: ...
@overload
def mean(a: ndarray[Any], *args: Any, **kwargs: Any) -> ndarray[Any]: ...
@overload
def mean(a: list[list[float]], *args: Any, **kwargs: Any) -> ndarray[Any]: ...
def dot(a: ndarray[Any] | list[float], b: ndarray[Any] | list[float]) -> float: ...
