"""Programmatic enrichment pipeline."""

python_sources(
    dependencies=[
        "//libs/enrichment/src/enrichment/api_helpers",
        "//libs/http_cache/src/http_cache",
        "//:reqs0#pydantic",
        "//:reqs0#pydantic-settings",
    ],
)
