# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from enrichment_proto.v1 import enrichment_service_pb2 as v1_dot_enrichment__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/enrichment_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnrichmentServiceStub(object):
    """RPCs for enrichment pipeline health and execution.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/enrichment_service.v1.EnrichmentService/Health',
                request_serializer=v1_dot_enrichment__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_enrichment__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_unary(
                '/enrichment_service.v1.EnrichmentService/RunPipeline',
                request_serializer=v1_dot_enrichment__service__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=v1_dot_enrichment__service__pb2.RunPipelineResponse.FromString,
                _registered_method=True)


class EnrichmentServiceServicer(object):
    """RPCs for enrichment pipeline health and execution.
    """

    def Health(self, request, context):
        """Returns service health/readiness information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """Runs the enrichment pipeline for one selected anime record.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrichmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_enrichment__service__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_enrichment__service__pb2.HealthResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=v1_dot_enrichment__service__pb2.RunPipelineRequest.FromString,
                    response_serializer=v1_dot_enrichment__service__pb2.RunPipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'enrichment_service.v1.EnrichmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('enrichment_service.v1.EnrichmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrichmentService(object):
    """RPCs for enrichment pipeline health and execution.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment_service.v1.EnrichmentService/Health',
            v1_dot_enrichment__service__pb2.HealthRequest.SerializeToString,
            v1_dot_enrichment__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment_service.v1.EnrichmentService/RunPipeline',
            v1_dot_enrichment__service__pb2.RunPipelineRequest.SerializeToString,
            v1_dot_enrichment__service__pb2.RunPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
