# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/enrichment_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v1/enrichment_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared_proto.v1 import error_pb2 as shared__proto_dot_v1_dot_error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bv1/enrichment_service.proto\x12\x15\x65nrichment_service.v1\x1a\x1bshared_proto/v1/error.proto\"\x0f\n\rHealthRequest\"v\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x65tails_json\x18\x03 \x01(\t\x12,\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x1d.shared_proto.v1.ErrorDetails\"\x95\x01\n\x12RunPipelineRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x12\n\x05index\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\r\n\x05title\x18\x03 \x01(\t\x12\x11\n\tagent_dir\x18\x04 \x01(\t\x12\x15\n\rskip_services\x18\x05 \x03(\t\x12\x15\n\ronly_services\x18\x06 \x03(\tB\x08\n\x06_index\"~\n\x13RunPipelineResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12,\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x1d.shared_proto.v1.ErrorDetails2\xd0\x01\n\x11\x45nrichmentService\x12U\n\x06Health\x12$.enrichment_service.v1.HealthRequest\x1a%.enrichment_service.v1.HealthResponse\x12\x64\n\x0bRunPipeline\x12).enrichment_service.v1.RunPipelineRequest\x1a*.enrichment_service.v1.RunPipelineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.enrichment_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=83
  _globals['_HEALTHREQUEST']._serialized_end=98
  _globals['_HEALTHRESPONSE']._serialized_start=100
  _globals['_HEALTHRESPONSE']._serialized_end=218
  _globals['_RUNPIPELINEREQUEST']._serialized_start=221
  _globals['_RUNPIPELINEREQUEST']._serialized_end=370
  _globals['_RUNPIPELINERESPONSE']._serialized_start=372
  _globals['_RUNPIPELINERESPONSE']._serialized_end=498
  _globals['_ENRICHMENTSERVICE']._serialized_start=501
  _globals['_ENRICHMENTSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
