"""Vector service package sources."""

python_sources(
    name="vector_service",
    dependencies=[
        "//apps/vector_service/src/vector_proto:proto",
        "//libs/common/src/shared_proto:proto",
        "//libs/common/src/common",
        "//libs/qdrant_db/src/qdrant_db",
        "//libs/vector_processing/src/vector_processing",
        "//:reqs0#grpcio",
        "//:reqs0#grpcio-health-checking",
    ],
)
