"""AniDB source — API helper."""

python_sources(
    dependencies=[
        "//libs/http_cache/src/http_cache",
        "//libs/common/src/common",
        "//libs/enrichment/src/enrichment/sources/base",
        "//:reqs0#aiohttp",
        "//:reqs0#defusedxml",
    ],
)
