"""Enrichment service package sources."""

python_sources(
    name="enrichment_service",
    dependencies=[
        "//apps/enrichment_service/src/enrichment_proto:proto",
        "//libs/common/src/shared_proto:proto",
        "//libs/common/src/common",
        "//libs/enrichment/src/enrichment",
        "//libs/http_cache/src/http_cache",
        "//:reqs0#grpcio",
        "//:reqs0#grpcio-health-checking",
    ],
)
