"""Service package sources."""

python_sources(
    dependencies=[
        "//libs/common/src/common",
        "//libs/qdrant_db/src/qdrant_db",
        "//libs/vector_processing/src/vector_processing",
        "//libs/http_cache/src/http_cache",
    ],
)
