python_tests(
    name="integration",
    dependencies=[
        "//:reqs0#pytest",
        "//:reqs0#pytest-asyncio",
        "libs/vector_db_interface/src/vector_db_interface:vector_db_interface",
    ],
)
