"""Enrichment utilities - Deduplication and text normalization."""

python_sources(
    dependencies=[
        "//libs/vector_processing/src/vector_processing",
        "//libs/common/src/common",
    ],
)
