"""Enrichment utilities unit tests."""

python_tests(
    dependencies=[
        "//tests/libs/enrichment/unit:conftest",
        "//libs/enrichment/src/enrichment",
        "//:reqs0#pytest-asyncio",
        "//:reqs0#pytest-mock",
    ],
)
