# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from vector_proto.v1 import vector_admin_pb2 as v1_dot_vector__admin__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in v1/vector_admin_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class VectorAdminServiceStub(object):
    """Administrative RPCs for health and runtime diagnostics."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/vector_service.v1.VectorAdminService/Health",
            request_serializer=v1_dot_vector__admin__pb2.HealthRequest.SerializeToString,
            response_deserializer=v1_dot_vector__admin__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.GetStats = channel.unary_unary(
            "/vector_service.v1.VectorAdminService/GetStats",
            request_serializer=v1_dot_vector__admin__pb2.GetStatsRequest.SerializeToString,
            response_deserializer=v1_dot_vector__admin__pb2.GetStatsResponse.FromString,
            _registered_method=True,
        )


class VectorAdminServiceServicer(object):
    """Administrative RPCs for health and runtime diagnostics."""

    def Health(self, request, context):
        """Returns service and dependency readiness information."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStats(self, request, context):
        """Returns operational vector database statistics as JSON."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VectorAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=v1_dot_vector__admin__pb2.HealthRequest.FromString,
            response_serializer=v1_dot_vector__admin__pb2.HealthResponse.SerializeToString,
        ),
        "GetStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetStats,
            request_deserializer=v1_dot_vector__admin__pb2.GetStatsRequest.FromString,
            response_serializer=v1_dot_vector__admin__pb2.GetStatsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "vector_service.v1.VectorAdminService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "vector_service.v1.VectorAdminService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class VectorAdminService(object):
    """Administrative RPCs for health and runtime diagnostics."""

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vector_service.v1.VectorAdminService/Health",
            v1_dot_vector__admin__pb2.HealthRequest.SerializeToString,
            v1_dot_vector__admin__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vector_service.v1.VectorAdminService/GetStats",
            v1_dot_vector__admin__pb2.GetStatsRequest.SerializeToString,
            v1_dot_vector__admin__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
