# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/vector_search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v1/vector_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vector_proto.v1 import vector_common_pb2 as v1_dot_vector__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16v1/vector_search.proto\x12\x11vector_service.v1\x1a\x16v1/vector_common.proto\"l\n\rSearchRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x13\n\x0b\x65ntity_type\x18\x03 \x01(\t\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x14\n\x0c\x66ilters_json\x18\x05 \x01(\t\"G\n\tSearchHit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10similarity_score\x18\x02 \x01(\x01\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\"l\n\x0eSearchResponse\x12*\n\x04hits\x18\x01 \x03(\x0b\x32\x1c.vector_service.v1.SearchHit\x12.\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1f.vector_service.v1.ErrorDetails2d\n\x13VectorSearchService\x12M\n\x06Search\x12 .vector_service.v1.SearchRequest\x1a!.vector_service.v1.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.vector_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=69
  _globals['_SEARCHREQUEST']._serialized_end=177
  _globals['_SEARCHHIT']._serialized_start=179
  _globals['_SEARCHHIT']._serialized_end=250
  _globals['_SEARCHRESPONSE']._serialized_start=252
  _globals['_SEARCHRESPONSE']._serialized_end=360
  _globals['_VECTORSEARCHSERVICE']._serialized_start=362
  _globals['_VECTORSEARCHSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
