# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/vector_admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "v1/vector_admin.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared_proto.v1 import error_pb2 as shared__proto_dot_v1_dot_error__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15v1/vector_admin.proto\x12\x11vector_service.v1\x1a\x1bshared_proto/v1/error.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x0f\n\rHealthRequest"\xcb\x01\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12)\n\x08\x64\x61tabase\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12,\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x1d.shared_proto.v1.ErrorDetails"\x11\n\x0fGetStatsRequest"T\n\x10GetStatsResponse\x12\x12\n\nstats_json\x18\x01 \x01(\t\x12,\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1d.shared_proto.v1.ErrorDetails2\xb8\x01\n\x12VectorAdminService\x12M\n\x06Health\x12 .vector_service.v1.HealthRequest\x1a!.vector_service.v1.HealthResponse\x12S\n\x08GetStats\x12".vector_service.v1.GetStatsRequest\x1a#.vector_service.v1.GetStatsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.vector_admin_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HEALTHREQUEST"]._serialized_start = 136
    _globals["_HEALTHREQUEST"]._serialized_end = 151
    _globals["_HEALTHRESPONSE"]._serialized_start = 154
    _globals["_HEALTHRESPONSE"]._serialized_end = 357
    _globals["_GETSTATSREQUEST"]._serialized_start = 359
    _globals["_GETSTATSREQUEST"]._serialized_end = 376
    _globals["_GETSTATSRESPONSE"]._serialized_start = 378
    _globals["_GETSTATSRESPONSE"]._serialized_end = 462
    _globals["_VECTORADMINSERVICE"]._serialized_start = 465
    _globals["_VECTORADMINSERVICE"]._serialized_end = 649
# @@protoc_insertion_point(module_scope)
