"""Anime-Planet crawler unit tests."""

python_tests(
    dependencies=[
        "//libs/enrichment/src/enrichment/crawlers/anime_planet",
        "//libs/common/src/common",
        "//tests/libs/enrichment/unit:conftest",
        "//:reqs0#pytest-asyncio",
        "//:reqs0#pytest-mock",
    ],
)
