"""Enrichment API helpers integration tests."""

python_tests(
    dependencies=[
        "//libs/enrichment/src/enrichment",
        "//libs/http_cache/src/http_cache",
        "//:reqs0#pytest-asyncio",
        "//:reqs0#pytest-mock",
    ],
)
