"""MAL crawler unit tests."""

python_tests(
    dependencies=[
        "//libs/enrichment/src/enrichment/crawlers/mal_crawler",
        "//libs/enrichment/src/enrichment/mappers",
        "//libs/common/src/common",
        "//:reqs0#pytest-asyncio",
        "//:reqs0#pytest-mock",
    ],
)
